### ISSUE TITLE
[REQUEST] Add an option for server (LAN) to allow spectators to see players's cards

### ISSUE THREAD

**Issue by Lightel24** [edo9300/ygopro-core#113]
Would it be possible to let the host choose if spectators can see players's cards or not?
It would be an option disabled by default.
I have not looked much into the code so i don't know how hard it would be to implement. And before even trying to implement it, i'd like to now if such option would be authorized.

Lightel

**Comment by DyXel** [comment]
The core has no concept of knowledge (hiding cards that are not public knowledge, hiding main deck, etc...). It is entirely done by the server (which lives on ygopro client code), by literally zeroing bytes on the binary buffer you receive when you call this core's C API. The place you would want to look at is [`generic_duel.cpp`](https://github.com/edo9300/edopro/blob/master/gframe/generic_duel.cpp).
