### ISSUE TITLE
Tons of compilation warnings

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro-core#41]

**Comment by AndreOliveiraMendes** [comment]
how manys warnings does it have atm?

**Comment by DyXel** [comment]
We must get rid of https://github.com/edo9300/ygopro-core/blob/688a05b98ac0647511bf683c9737ce8389cfb032/common.h#L12

and also possibly enable -Wall, -Wextra and/or -pedantic for gcc compiler

**Comment by kevinlul** [comment]
TODO: Per #44, convert all `size_t` to appropriate types.

**Comment by kevinlul** [comment]
Last warnings on the `master` branch are on MSVC and should be closed by end of day. Should we suppress CRT insecure warnings such as using `strcat`?
