### ISSUE TITLE
Damage value overflow with Dark Snake Syndrome

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro-core#68]
Originally reported June 9:

When a certain maximum threshold of damage is reached with Dark Snake Syndrome, the effect stops activating.

[Puzzle](https://cdn.discordapp.com/attachments/291708361752313866/291723338022387714/Darksnake_break.lua)

**Comment by kevinlul** [comment]
The threshold is `2^31 - 1 = 2147483647`, beyond which nothing happens. At this threshold though the actual value is `16777215 = 2^24 - 1` and in fact values beyond that sometimes do nothing. This is the same issue with overflow as #67 fundamentally

**Comment by AndreOliveiraMendes** [comment]
oh, actualy damage/recover caps is lower than actual lp limit, if i remeber it 0xfffff
this is most due to how core send message from what i remember, the damage param pass trought &0xfffff before passing it.

**Comment by kevinlul** [comment]
Yeah, I found it in the processor that's restricting it to 24 bits, so with the right values it'll just zero out. The actual `field::recover` function is not being called in cases.

**Comment by AndreOliveiraMendes** [comment]
i wonder if we can even do something about it, at least to make it the same as lp limit, but i don't think that there no way to do unlimited.

**Comment by DyXel** [comment]
my suggestion would be to put a syntatic limit of `999999999` and remove the limitations from `MSG_DAMAGE`, `MSG_RECOVER`, `MSG_LPUPDATE` and `MSG_PAY_LPCOST`

**Comment by AndreOliveiraMendes** [comment]
the restriction is more that every arguments are all put on arg2 (same thing they do with pendulum scale), if they were separated maybe the limit would be at least same as lp.
