### ISSUE TITLE
Duel.GetBattleDamage ignores some effects causing incorrect interactions

### ISSUE THREAD

**Issue by AlphaKretin** [edo9300/ygopro-core#71]
Compilation of issues originally opened June 7, June 9
Examples:
- If "Blue-Eyes Chaos MAX Dragon" (`Duel.DoublePiercingDamage`) attacks a Defense Position 0 DEF monster, it will do 8000 Damage. However, "Power Wall" (`Duel.GetBattleDamage`) will see 4000 Damage and send only 8 cards, not 16 (`dam//500`).
- With "Lyrilusc - Assembled Nightingale" applied (`EFFECT_AVOID_BATTLE_DAMAGE`), "Amazoness Swords Woman" (`Duel.GetBattleDamage`) still does "reflected" battle damage to the opponent. 
- "Defense Draw" ('Duel.GetBattleDamage') without a flag-based workaround will still draw a card after "change battle damage to 0, and if you do" if damage has already been changed to 0 by another "Defense Draw" (`Duel. ChangeBattleDamage`).

See puzzle 62 for "Defense Draw" and 71 for "Assembled Nightingale".

**Comment by edo9300** [comment]
The issue here is the way lua functions are called, the exact same parameters are passed to every effect solving, so there's no value synchronization between them. The only suitable handling is the one with the external functions to store the changes

**Comment by NaimSantos** [comment]
@AlphaKretin 
I confirmed that with the latest changes the issue with `Lyrilusc - Assembled Nightingale vs Amazoness Swordswoman` and `Blue-Eyes Chaos MAX Dragon vs Power Wall` were fixed, but the bug with `Defense Draw` remains.

**Comment by edo9300** [comment]
The way of handling such cards was changed, this function should not be called when dealing with an effect changing the battle damage
