### ISSUE TITLE
Servant/Magister/Reflection of Endymion

### ISSUE THREAD

**Issue by NaimSantos** [edo9300/ygopro-core#74]
If the activation of their Pendulum effect is negated, then you should be able to use it again on the same turn (D/D/D Flame High King Genghis), but if only the effect is negated then you shouldn't be able to use the effect again on the same turn (Ash Blossom & Joyous Spring), because of You can only Special Summon "Servant(s)/Magister(s)/Reflection(s) of Endymion" once per turn.
[Puzzle to test](https://cdn.discordapp.com/attachments/280403281308680192/582641648396140554/servant_only_once.lua)

Seems like a core bug, [possibly related fix commit on fluo](https://github.com/Fluorohydride/ygopro-core/commit/b94f0ed98d1507406ed499b7b8ae7bc6565eec36)

See puzzle 85

**Comment by NaimSantos** [comment]
#https://github.com/YgoproStaff/Edopro_1034/issues/85

**Comment by edo9300** [comment]
This issue is caused by a wrong script, not a core bug. The cards to be summoned aren't being set as such, so their spsummon once is never set
