### ISSUE TITLE
Subterror Nemesis Warrior workaround

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro-core#85]
The player isn't prompted to activate Warrior's effect from the Graveyard if your "Subterror Behemoth" is flipped face-up when attacked and then destroyed after (during Before Damage Calculation in this example) by an effect like Drillroid's. The Behemoth's FLIP effect triggers normally as it should in this scenario.

[Replay from Percy](https://cdn.discordapp.com/attachments/319195768693063684/450418397344170015/nemesis_warrior_drillroid.yrp). Also see puzzle 46 from @AlphaKretin. Adding `EFFECT_FLAG_DAMAGE_CAL` to both relevant places in Warrior's script also didn't seem to fix it. Incidentally, Warrior seems to use some massive workaround, perhaps there could or is supposed to be a core change to simplify and fix things

Originally reported Jun 6

**Comment by edo9300** [comment]
This interaction works correctly, the issue is percy only
