### ISSUE TITLE
Summoning Inspector Boarder

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro-core#86]
You can Special Summon an opponent's Inspector Boarder with Monster Reborn when you control a monster, which should not happen. [Source](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=13650&keyword=&tag=-1)
[Puzzle](https://cdn.discordapp.com/attachments/291708361752313866/512780287839698945/InspectorBoard.lua) also see puzzle 70

The issue is because the summon condition is checking the effect's handler player. Checking `c76614340.lua`, the condition can take extra parameters: `function s.splimit(e,se,sp,st)`. I would guess that `sp` is the summon player, and boarder should check that instead of `e:GetHandlerPlayer()`. I don't know if the different effect for locking Normal Summons has the same parameters, but in that case, they can just use different conditions, because only the handler player can normal summon it. @AlphaKretin
E: This assessment was based on the Percy script, its script here is different.

OK, after a bunch of confused testing, I've determined that `sp` is `nil` in the following function.
```lua
--summon limit
local e1=Effect.CreateEffect(c)
e1:SetType(EFFECT_TYPE_SINGLE)
e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
e1:SetCode(EFFECT_CANNOT_SUMMON)
e1:SetCondition(s.sumcon)
c:RegisterEffect(e1)
local e2=e1:Clone()
e2:SetCode(EFFECT_SPSUMMON_CONDITION)
c:RegisterEffect(e2)
function s.sumcon(e,se,sp,st)
	Debug.Message(sp)
	return Duel.GetFieldGroupCount(sp,LOCATION_MZONE,0)>0
end
```
This would also explain why the summoning restriction wasn't working at all with the Edopro script. The fix for this might require exposing such parameters in the core. -Alpha

Jun 6-9

**Comment by edo9300** [comment]
Fixed in https://github.com/kevinlul/edopro-script/commit/031805026f2a64ea32423594a309f6c12b059ad0, this was a script issue
