### ISSUE TITLE
GetLink returns 0 if the card is in the S/T Zone

### ISSUE THREAD

**Issue by NaimSantos** [edo9300/ygopro-core#88]
If `Borreload Savage Dragon` equips a link monster to itself, it does not get any counters. The `GetLink` function returns 0 if the card is in the S/T Zone, probably related with the changes due to the implementation of Link Spells

**Comment by AlphaKretin** [comment]
It sounds like we could use a function like `GetOriginalLink()`, which doesn’t seem to exist.

**Comment by kevinlul** [comment]
To investigate

https://github.com/edo9300/ygopro-core/commit/fd6bb84eda625a022d735cc6c1f40c7a04d37f8b
https://github.com/edo9300/ygopro-core/commit/3317b71b08d5af4057e1311a717d9bd9ed799802

**Comment by NaimSantos** [comment]
Do we have any reply about this from @edo9300 ? The problem exist in the client and 33 cards and the link summon procedure are using the GetLink function.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro-core/commit/8778201614ac913dfb5b60924310439c96a80b95
