### ISSUE TITLE
MSG_SWAP_GRAVE_DECK depends on client state

### ISSUE THREAD

**Issue by DyXel** [edo9300/ygopro-core#91]
The problem is that the client must have the database(s) which have the data of cards that get swapped from the graveyard to either deck or extra deck, the client checks if the card is a extra deck card before moving it, something that should be done on the core. In the event that the client doesn't have the data of the card, the game will end up on a invalid state (It will send a extra deck card to the main deck, thus resulting on a invalid count)

Exchange of the Spirit is only card that uses this message, furthermore, is the only message that has this issue.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro-core/commit/081abc4b18b8ec186fa77ab0cdf00c9666be6c74
