### ISSUE TITLE
Add player parameter to Effect.SetCountLimit

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro-core#97]
Hard-once-per-turn effects are tracked per card instance instead of per card instance AND per player.

**Example:**

Turn 2
Used Widow Anchor to take control of Frodi, Generaider Boss of Swords, which already used its effect. The opponent cannot attempt to activate Frodi's effect again, which is incorrect.

[Replay](https://cdn.discordapp.com/attachments/184324960842416129/658306461423763477/Widow.yrp)

**Comment by AndreOliveiraMendes** [comment]
oh, so this explain things, would it be hard to change?

**Comment by edo9300** [comment]
This change is unneeded, or better, that's not the way to solve this issue, the player is already checked internally, also, adding a player parameter would be, pointless? Also would not work, because that'd mean that the count limit would affect that player

**Comment by edo9300** [comment]
Issue not happening in edopro
