### ISSUE TITLE
Card.IsLinked behaves incorrectly

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro-core#98]
Linked cards to the specified card are identified incorrectly. For example, in the Pentestag puzzle, monsters linked to Pentestag fail to inflict piercing battle damage.

**Comment by AlphaKretin** [comment]
Specifically, a mistake in the implantation for Link spells requires that a card be of `TYPE_LINK` *and* in the monster zone, rather than *or* (because a non-Link Spell/Trap cannot be Linked).

**Comment by AlphaKretin** [comment]
Fixed in https://github.com/edo9300/ygopro-core/commit/87af388855c782c4fcdfd198bdff38d7083b078b
